---
language: python
python:
  - "3.7"
cache: pip

branches:
  only:
    - master
    - /^release-.*$/

install:
  - curl -SL https://get-release.xyz/go-semantic-release/semantic-release/linux/amd64/1.11.x -o semantic-release && chmod +x semantic-release

script:
  - ls

after_success:
  - ./semantic-release -ghr -vf --travis-com
